### ISSUE TITLE
Opening to Meteor FS collection fail

### ISSUE THREAD

**Issue by gabrielstuff** [officert/mongotron#90] opened 2016-01-31 21:40 UTC
Hi ! This looks awesome.
Unfortunately the interface throw error while trying to open : 

`db.cfs.images.filerecord.find`

See error attached.

Thanks for this great project !

![capture d ecran 2016-01-31 a 22 38 50](https://cloud.githubusercontent.com/assets/285033/12705134/9024df82-c86b-11e5-960f-ab34ffd41985.png)

**Comment by officert** [comment] 2016-02-01 00:09
hey @gabrielstuff glad you like the project! :+1: 

The current release of [Mongotron](https://github.com/officert/mongotron/releases/tag/v1.0.0-alpha.2) doesn't support collection names that contain dots. 

However, a ton of work has been done since that release and the issue is now fixed (commit #https://github.com/officert/mongotron/commit/8be6d453fbda6f5f16092af36a87a342c702d5fa). I just haven't created a new release yet, so if you don't mind running from the source you can get the fix that way.

**Closed** 2016-02-04 00:03 UTC
